### ISSUE TITLE
Details on bWF0cnlvc2hrYQ== challenge

### ISSUE THREAD

**Issue by foudfou** [kuqadk3/CTF-and-Learning#3]
Thx for the cool writeups!
Could you elaborate a bit in [the BSides matryoshka challenge](/kuqadk3/CTF-and-Learning/blob/master/bsidessf-2019-ctf.md) on how to extract the image properly ? I was also stuck at this stage. I tried extracting with `qpfd`, libreoffice save, `pdfimages`, `pdfextract` then apply `Stegsolve` on them. Without luck.
Also you mention:

> just do pixel subtract

and seem to use some java tool to do it. Which one is it ?

**Comment by kuqadk3** [comment]
I was use a tool online to extract image, couldnt remember. Though there is more proper way to do it is deflate the data in pdf.

The tool i used for subtract pixel is StegSolver

**Comment by foudfou** [comment]
Then I must have not properly extracted the image :) Thanks for your answer
